ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sockudo.ci.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sockudo-tls
      hosts:
        - sockudo.ci.example.com
wsIngress:
  enabled: true
  className: nginx
  hosts:
    - host: ws.sockudo.ci.example.com
      paths:
        - path: /
          pathType: Prefix
